const pois = [
    { "lat": "47.268827", "lng": "11.393310", "name": "Goldenes Dachl", "what": "Das Wahrzeichen der Stadt! </br> Hier gibt es auch ein <a href='https://www.innsbruck.gv.at/goldenesdachl/'>Museum</a>.", "adresse": "Herzog-Friedrich-Straße 15 </br> 6020 Innsbruck" },
    { "lat": "47.256794", "lng": "11.433597", "name": "Schloss Ambras", "what": "Nationalmuseum mit Porträtsammlungen, Kunstwerken und Rüstkammer im Schloss aus der Spätrenaissance.</br>Für mehr Infos klicke <a href='https://www.schlossambras-innsbruck.at/'>hier</a>.", "adresse": "Schloßstraße 20 </br> 6020 Innsbruck" },
    { "lat": "47.254598", "lng": "11.388194", "name": "Kleinbrauerei Tiroler Bier", "what": "Brauerei Baumgartner Harald 'Tiroler Bier' ist eine kleine Brauerei in Innsbruck, die seit 1999 besteht und ihr Bier gerne unter die Leute bring. Schau doch mal <a href='http://www.tirolerbier.at/index.html'>vorbei</a> - Prost!", "adresse": "Feldstraße 11a </br> 6020 Innsbruck" },
    { "lat": "47.262866", "lng": "11.394777", "name": "Triumphpforte", "what": "Der Name ist Programm - die Triumphpforte gehört eindeutig zu den bekanntesten Sehenswürdigkeiten der Stadt. Sie liegt am südlichen Ende der Fußgängerzone (Maria-Theresien-Straße) und wurde 1765 aus Anlass der Hochzeit von Erzherzog Leopold, dem zweiten Sohn von Kaiserin Maria Theresia und Franz Stephan von Lothringen, mit der spanischen Prinzessin Maria Ludovica erbaut. ", "adresse": "Leopoldstraße 2</br> 6020 Innsbruck" },
    { "lat": "47.268011", "lng": "11.390596", "name": "Marktplatz", "what": "Der Marktplatz selbst besticht nicht durch Originalität - ein Aufenthalt lohnt sich eigentlich nur in einem der Liegestühle an der Sonnenterasse der angrenzenden Markthallen, oder wenn eine Veranstaltung die Teerfläche belebt. </br> Ein Besuch lohnt trotzdem - der Blick über den Inn auf die bunten Häuserfasaden mit der Nordkette im Hintergrund zählt zu den beliebtesten Fotomotiven der Stadt.", "adresse": "Innrain 2</br> 6020 Innsbruck" },
    { "lat": "47.269573", "lng": "11.394248", "name": "Innsbrucker Dom", "what": "Der Dom zu St. Jakob in Innsbruck zählt zu den Wahrzeichen der Stadt und ist die Kathedrale beziehungsweise der Bischofssitz der römisch-katholischen Diözese Innsbruck. Seine Türme prägen die Innsbrucker <i>Skyline</i> und der schattige Vorplatz läd zum Eisessen ein.", "adresse": "Domplatz 7</br> 6020 Innsbruck" },
    { "lat": "47.263538", "lng": "11.396801", "name": "Audioversum", "what": "Das AUDIOVERSUM ist die interaktive Erlebniswelt zum Hören und Staunen in Innsbruck. Als Science Center verbindet es Medizin, Technik, Bildung und Kunst und fasziniert Besucherinnen und Besucher aus dem In- und Ausland. Multimediale Installationen, in Kooperation mit dem renommierten Ars Electronica Center Linz entwickelt, laden zum Mitmachen ein und schärfen die Sinne.", "adresse": "Wilhelm-Greil-Straße 23</br> 6020 Innsbruck" },
];
